option(
	'target',
	type: 'array',
	choices: [
		'stm32f0',
		'stm32f1',
		'stm32f2',
		'stm32f3',
		'stm32f4',
		'stm32f7',
		'stm32g0',
		'stm32g4',
		'stm32h7',
		'stm32l0',
		'stm32l1',
		'stm32l4',
		'stm32u5',
		'gd32f1x0',
		'lpc13xx',
		'lpc17xx',
		'lpc43xxm0',
		'lpc43xxm4',
		'nrf51',
		'nrf52',
		'efm32tg',
		'efm32g',
		'efm32lg',
		'efm32gg',
		'efm32hg',
		'efm32wg',
		'ezr32wg',
		'msp432e4',
		'lm4f',
	],
	value: [
		'stm32f0',
		'stm32f1',
		'stm32f2',
		'stm32f3',
		'stm32f4',
		'stm32f7',
		'stm32g0',
		'stm32g4',
		'stm32h7',
		'stm32l0',
		'stm32l1',
		'stm32l4',
		'stm32u5',
		'gd32f1x0',
		'lpc13xx',
		'lpc17xx',
		'lpc43xxm0',
		'lpc43xxm4',
		'nrf51',
		'nrf52',
		'efm32tg',
		'efm32g',
		'efm32lg',
		'efm32gg',
		'efm32hg',
		'efm32wg',
		'ezr32wg',
		'msp432e4',
		'lm4f',
	],
	description: 'The hardware platforms you wish to target'
)
