if 'efm32tg' in target_platforms
	subdir('tg')
endif
if 'efm32g' in target_platforms
	subdir('g')
endif
if 'efm32lg' in target_platforms
	subdir('lg')
endif
if 'efm32gg' in target_platforms
	subdir('gg')
endif
if 'efm32hg' in target_platforms
	subdir('hg')
endif
if 'efm32wg' in target_platforms
	subdir('wg')
endif
if 'ezr32wg' in target_platforms
	subdir('ezr32wg')
endif
