name: Build and Deploy Documentation

on:
  push:
    branches: [ master, main, github-actions ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allow manual triggering

env:
  # Use ARM GCC toolchain for building
  ARM_TOOLCHAIN_VERSION: "14.3.Rel1"

jobs:
  build-all:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Cache ARM toolchain
      id: cache-arm-toolchain
      uses: actions/cache@v4
      with:
        path: /opt/arm-toolchain
        key: arm-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}
    
    - name: Install ARM GCC toolchain
      if: steps.cache-arm-toolchain.outputs.cache-hit != 'true'
      run: |
        cd /tmp
        wget -q "https://developer.arm.com/-/media/Files/downloads/gnu/${{ env.ARM_TOOLCHAIN_VERSION }}/binrel/arm-gnu-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}-x86_64-arm-none-eabi.tar.xz"
        sudo mkdir -p /opt/arm-toolchain
        sudo tar -xf arm-gnu-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}-x86_64-arm-none-eabi.tar.xz -C /opt/arm-toolchain --strip-components=1

    - name: Install Doxygen and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz python3 python3-pip
    
    - name: Add ARM toolchain to PATH
      run: echo "/opt/arm-toolchain/bin" >> $GITHUB_PATH
    
    - name: Verify programm versions
      run: |
        arm-none-eabi-gcc --version
        arm-none-eabi-objcopy --version
        doxygen --version
        python3 --version
    
    - name: Build libopencm3 libraries
      run: |
        echo "Building libopencm3 libraries..."
        make -j$(nproc) lib
        echo "Library build completed successfully"
    
    - name: Upload library artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libopencm3-libraries
        path: |
          lib/**/*.a
          lib/**/*.ld
          include/
        retention-days: 30
        compression-level: 6
    
    - name: Run basic tests
      run: |
        echo "Running basic validation..."
        
        # Check that key libraries were built successfully
        echo "Checking STM32 libraries..."
        test -f lib/stm32/f0/libopencm3_stm32f0.a && echo "✅ STM32F0 library built"
        test -f lib/stm32/f1/libopencm3_stm32f1.a && echo "✅ STM32F1 library built"
        test -f lib/stm32/f2/libopencm3_stm32f2.a && echo "✅ STM32F2 library built"
        test -f lib/stm32/f3/libopencm3_stm32f3.a && echo "✅ STM32F3 library built"
        test -f lib/stm32/f4/libopencm3_stm32f4.a && echo "✅ STM32F4 library built"
        test -f lib/stm32/f7/libopencm3_stm32f7.a && echo "✅ STM32F7 library built"
        test -f lib/stm32/l0/libopencm3_stm32l0.a && echo "✅ STM32L0 library built"
        test -f lib/stm32/l1/libopencm3_stm32l1.a && echo "✅ STM32L1 library built"
        test -f lib/stm32/l4/libopencm3_stm32l4.a && echo "✅ STM32L4 library built"
        test -f lib/stm32/g0/libopencm3_stm32g0.a && echo "✅ STM32G0 library built"
        test -f lib/stm32/g4/libopencm3_stm32g4.a && echo "✅ STM32G4 library built"
        test -f lib/stm32/h7/libopencm3_stm32h7.a && echo "✅ STM32H7 library built"
        test -f lib/stm32/u5/libopencm3_stm32u5.a && echo "✅ STM32U5 library built"
        
        echo "Checking other microcontroller libraries..."
        test -f lib/gd32/f1x0/libopencm3_gd32f1x0.a && echo "✅ GD32F1x0 library built"
        test -f lib/lpc13xx/libopencm3_lpc13xx.a && echo "✅ LPC13XX library built"
        test -f lib/lpc17xx/libopencm3_lpc17xx.a && echo "✅ LPC17XX library built"
        test -f lib/lpc43xx/m0/libopencm3_lpc43xx_m0.a && echo "✅ LPC43XX M0 library built"
        test -f lib/lpc43xx/m4/libopencm3_lpc43xx_m4.a && echo "✅ LPC43XX M4 library built"
        test -f lib/lm3s/libopencm3_lm3s.a && echo "✅ LM3S library built"
        test -f lib/lm4f/libopencm3_lm4f.a && echo "✅ LM4F library built"
        test -f lib/msp432/e4/libopencm3_msp432e4.a && echo "✅ MSP432E4 library built"
        
        echo "Checking EFM32 libraries..."
        test -f lib/efm32/tg/libopencm3_efm32tg.a && echo "✅ EFM32TG library built"
        test -f lib/efm32/g/libopencm3_efm32g.a && echo "✅ EFM32G library built"
        test -f lib/efm32/lg/libopencm3_efm32lg.a && echo "✅ EFM32LG library built"
        test -f lib/efm32/gg/libopencm3_efm32gg.a && echo "✅ EFM32GG library built"
        test -f lib/efm32/hg/libopencm3_efm32hg.a && echo "✅ EFM32HG library built"
        test -f lib/efm32/wg/libopencm3_efm32wg.a && echo "✅ EFM32WG library built"
        test -f lib/efm32/ezr32wg/libopencm3_efm32ezr32wg.a && echo "✅ EFM32EZR32WG library built"
        
        echo "Checking Nordic and Atmel libraries..."
        test -f lib/nrf/51/libopencm3_nrf51.a && echo "✅ NRF51 library built"
        test -f lib/nrf/52/libopencm3_nrf52.a && echo "✅ NRF52 library built"
        test -f lib/sam/3a/libopencm3_sam3a.a && echo "✅ SAM3A library built"
        test -f lib/sam/3n/libopencm3_sam3n.a && echo "✅ SAM3N library built"
        test -f lib/sam/3s/libopencm3_sam3s.a && echo "✅ SAM3S library built"
        test -f lib/sam/3u/libopencm3_sam3u.a && echo "✅ SAM3U library built"
        test -f lib/sam/3x/libopencm3_sam3x.a && echo "✅ SAM3X library built"
        test -f lib/sam/4l/libopencm3_sam4l.a && echo "✅ SAM4L library built"
        test -f lib/sam/d/libopencm3_samd.a && echo "✅ SAMD library built"
        
        echo "Checking remaining libraries..."
        test -f lib/vf6xx/libopencm3_vf6xx.a && echo "✅ VF6XX library built"
        test -f lib/swm050/libopencm3_swm050.a && echo "✅ SWM050 library built"
        test -f lib/pac55xx/libopencm3_pac55xx.a && echo "✅ PAC55XX library built"
        
        echo "✅ All library validation tests completed successfully!"
    
    - name: Build documentation
      run: |
        echo "Building documentation..."
        make doc

    - name: Check for Doxygen warnings
      run: |
        cd doc
        echo "Checking for Doxygen warnings..."
        
        # Check if there are any warnings
        for target_dir in */; do
          if [ -d "$target_dir/html" ] && [ "$target_dir" != "templates/" ]; then
            echo "Checking $target_dir for warnings..."
            if [ -f "$target_dir/doxygen.log" ]; then
              
              # Check for errors in the Doxygen log            
              if grep -q "error:" "$target_dir/doxygen.log"; then
                echo "❌ Doxygen errors found in $target_dir:"
                grep "error:" "$target_dir/doxygen.log" || true
                exit 1

              # Check for warnings in the Doxygen log
              elif grep -q "warning:" doxygen_warnings.log; then
                echo "⚠️ Doxygen warnings found in $target_dir:"
                grep "warning:" "$target_dir/doxygen.log" || true
                echo "Please review and fix these warnings to improve documentation quality."
                # Don't fail the build on warnings, just report them
              
              else
                echo "✅ No Doxygen warnings found in $target_dir!"
              fi
            fi
          fi
        done
    
    - name: Prepare deployment files
      run: |
        cd doc
        echo "Preparing documentation for deployment..."
        
        # Create deployment directory
        mkdir -p ../deploy
        
        # Copy main documentation
        if [ -d "html" ]; then
          echo "Copying main documentation..."
          cp -r html ../deploy/
        else
          echo "Warning: Main html directory not found"
        fi
        
        # Copy target-specific documentation
        echo "Copying target-specific documentation..."
        for target_dir in */; do
          if [ -d "$target_dir/html" ] && [ "$target_dir" != "templates/" ]; then
            echo "Copying $target_dir documentation..."
            mkdir -p "../deploy/$target_dir"
            cp -r "$target_dir/html" "../deploy/$target_dir/"
          fi
        done
        
        # Filter out build artifacts and unnecessary files
        echo "Cleaning up deployment files..."
        cd ../deploy
        
        # Remove Doxygen build artifacts
        find . -name "*.md5" -delete 2>/dev/null || true
        find . -name "*.map" -delete 2>/dev/null || true
        find . -name "*.tmp" -delete 2>/dev/null || true
        find . -name "doxy.sourcelist" -delete 2>/dev/null || true
        find . -name "Doxyfile" -delete 2>/dev/null || true
        find . -name "DoxygenLayout_*.xml" -delete 2>/dev/null || true
        find . -name "doxygen_*.log" -delete 2>/dev/null || true
        find . -name "*.tag" -delete 2>/dev/null || true
        
        # Remove backup and temporary files
        find . -name "*~" -delete 2>/dev/null || true
        find . -name "*.bak" -delete 2>/dev/null || true
        find . -name ".DS_Store" -delete 2>/dev/null || true
        
        echo "Deployment preparation completed"
        
        # Show deployment statistics
        echo "Deployment statistics:"
        echo "  HTML files: $(find . -name "*.html" | wc -l)"
        echo "  CSS files:  $(find . -name "*.css" | wc -l)"
        echo "  JS files:   $(find . -name "*.js" | wc -l)"
        echo "  Image files: $(find . -name "*.png" -o -name "*.gif" -o -name "*.svg" -o -name "*.jpg" | wc -l)"
        echo "  Total size: $(du -sh . | cut -f1)"
   
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: libopencm3-documentation
        path: deploy/
        retention-days: 30
        compression-level: 6
    