name: Build and Deploy Documentation

on:
  push:
    branches: [ master, main, github-actions ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allow manual triggering

env:
  # Use ARM GCC toolchain for building
  ARM_TOOLCHAIN_VERSION: "14.3.Rel1"

jobs:
  build-all:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Cache ARM toolchain
      id: cache-arm-toolchain
      uses: actions/cache@v4
      with:
        path: /opt/arm-toolchain
        key: arm-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}
    
    - name: Install ARM GCC toolchain
      if: steps.cache-arm-toolchain.outputs.cache-hit != 'true'
      run: |
        cd /tmp
        wget -q "https://developer.arm.com/-/media/Files/downloads/gnu/${{ env.ARM_TOOLCHAIN_VERSION }}/binrel/arm-gnu-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}-x86_64-arm-none-eabi.tar.xz"
        sudo mkdir -p /opt/arm-toolchain
        sudo tar -xf arm-gnu-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}-x86_64-arm-none-eabi.tar.xz -C /opt/arm-toolchain --strip-components=1

    - name: Install Doxygen and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz python3 python3-pip
    
    - name: Add ARM toolchain to PATH
      run: echo "/opt/arm-toolchain/bin" >> $GITHUB_PATH
    
    - name: Verify programm versions
      run: |
        arm-none-eabi-gcc --version
        arm-none-eabi-objcopy --version
        doxygen --version
        python3 --version
    
    - name: Build libopencm3 libraries
      run: |
        echo "Building libopencm3 libraries..."
        make -j$(nproc) lib
        echo "Library build completed successfully"
    
    - name: Upload library artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libopencm3-libraries
        path: |
          lib/**/*.a
          lib/**/*.ld
          include/
        retention-days: 30
        compression-level: 6
    
    - name: Run basic tests
      run: |
        echo "Running basic validation..."
        
        # Set exit on error
        set -e
        
        # Track test results
        failed_tests=0
        
        # Check that key libraries were built successfully
        echo "Checking STM32 libraries..."
        test -f lib/libopencm3_stm32f0.a && echo "✅ STM32F0 library built" || { echo "❌ STM32F0 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32f1.a && echo "✅ STM32F1 library built" || { echo "❌ STM32F1 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32f2.a && echo "✅ STM32F2 library built" || { echo "❌ STM32F2 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32f3.a && echo "✅ STM32F3 library built" || { echo "❌ STM32F3 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32f4.a && echo "✅ STM32F4 library built" || { echo "❌ STM32F4 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32f7.a && echo "✅ STM32F7 library built" || { echo "❌ STM32F7 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32l0.a && echo "✅ STM32L0 library built" || { echo "❌ STM32L0 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32l1.a && echo "✅ STM32L1 library built" || { echo "❌ STM32L1 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32l4.a && echo "✅ STM32L4 library built" || { echo "❌ STM32L4 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32g0.a && echo "✅ STM32G0 library built" || { echo "❌ STM32G0 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32g4.a && echo "✅ STM32G4 library built" || { echo "❌ STM32G4 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32h7.a && echo "✅ STM32H7 library built" || { echo "❌ STM32H7 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_stm32u5.a && echo "✅ STM32U5 library built" || { echo "❌ STM32U5 library missing"; failed_tests=$((failed_tests + 1)); }
        
        echo "Checking LPC libraries..."
        test -f lib/libopencm3_lpc13xx.a && echo "✅ LPC13XX library built" || { echo "❌ LPC13XX library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_lpc17xx.a && echo "✅ LPC17XX library built" || { echo "❌ LPC17XX library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_lpc43xx.a && echo "✅ LPC43XX M0 library built" || { echo "❌ LPC43XX M0 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_lpc43xx_m4.a && echo "✅ LPC43XX M4 library built" || { echo "❌ LPC43XX M4 library missing"; failed_tests=$((failed_tests + 1)); }

        echo "Checking NXP Kinetis libraries..."
        test -f lib/libopencm3_lm3s.a && echo "✅ LM3S library built" || { echo "❌ LM3S library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_lm4f.a && echo "✅ LM4F library built" || { echo "❌ LM4F library missing"; failed_tests=$((failed_tests + 1)); }

        echo "Checking MSP432 libraries..."
        test -f lib/libopencm3_msp432e4.a && echo "✅ MSP432E4 library built" || { echo "❌ MSP432E4 library missing"; failed_tests=$((failed_tests + 1)); }
        
        echo "Checking EFM32 libraries..."
        test -f lib/libopencm3_efm32tg.a && echo "✅ EFM32TG library built" || { echo "❌ EFM32TG library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_efm32g.a && echo "✅ EFM32G library built" || { echo "❌ EFM32G library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_efm32lg.a && echo "✅ EFM32LG library built" || { echo "❌ EFM32LG library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_efm32gg.a && echo "✅ EFM32GG library built" || { echo "❌ EFM32GG library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_efm32hg.a && echo "✅ EFM32HG library built" || { echo "❌ EFM32HG library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_efm32wg.a && echo "✅ EFM32WG library built" || { echo "❌ EFM32WG library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_ezr32wg.a && echo "✅ EFM32EZR32WG library built" || { echo "❌ EFM32EZR32WG library missing"; failed_tests=$((failed_tests + 1)); }
        
        echo "Checking Nordic libraries..."
        test -f lib/libopencm3_nrf51.a && echo "✅ NRF51 library built" || { echo "❌ NRF51 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_nrf52.a && echo "✅ NRF52 library built" || { echo "❌ NRF52 library missing"; failed_tests=$((failed_tests + 1)); }

        echo "Checking Atmel SAM libraries..."
        test -f lib/libopencm3_sam3a.a && echo "✅ SAM3A library built" || { echo "❌ SAM3A library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_sam3n.a && echo "✅ SAM3N library built" || { echo "❌ SAM3N library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_sam3s.a && echo "✅ SAM3S library built" || { echo "❌ SAM3S library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_sam3u.a && echo "✅ SAM3U library built" || { echo "❌ SAM3U library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_sam3x.a && echo "✅ SAM3X library built" || { echo "❌ SAM3X library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_sam4l.a && echo "✅ SAM4L library built" || { echo "❌ SAM4L library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_samd.a && echo "✅ SAMD library built" || { echo "❌ SAMD library missing"; failed_tests=$((failed_tests + 1)); }
        
        echo "Checking other libraries..."
        test -f lib/libopencm3_vf6xx.a && echo "✅ VF6XX library built" || { echo "❌ VF6XX library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_swm050.a && echo "✅ SWM050 library built" || { echo "❌ SWM050 library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_pac55xx.a && echo "✅ PAC55XX library built" || { echo "❌ PAC55XX library missing"; failed_tests=$((failed_tests + 1)); }
        test -f lib/libopencm3_gd32f1x0.a && echo "✅ GD32F1x0 library built" || { echo "❌ GD32F1x0 library missing"; failed_tests=$((failed_tests + 1)); }
        
        # Report final results
        if [ $failed_tests -eq 0 ]; then
          echo "✅ All library validation tests completed successfully!"
        else
          echo "❌ $failed_tests library validation tests failed!"
          echo "Build validation failed - some expected libraries were not built."
          exit 1
        fi
    
    - name: Build documentation
      run: |
        echo "Building documentation..."
        make doc

    - name: Check for Doxygen warnings
      run: |
        cd doc
        echo "Checking for Doxygen warnings..."
        
        # Check if there are any warnings
        for target_dir in */; do
          if [ -d "$target_dir/html" ] && [ "$target_dir" != "templates/" ]; then
            echo "Checking $target_dir for warnings..."
            if [ -f "$target_dir/doxygen.log" ]; then
              
              # Check for errors in the Doxygen log            
              if grep -q "error:" "$target_dir/doxygen.log"; then
                echo "❌ Doxygen errors found in $target_dir:"
                grep "error:" "$target_dir/doxygen.log" || true
                exit 1

              # Check for warnings in the Doxygen log
              elif grep -q "warning:" doxygen_warnings.log; then
                echo "⚠️ Doxygen warnings found in $target_dir:"
                grep "warning:" "$target_dir/doxygen.log" || true
                echo "Please review and fix these warnings to improve documentation quality."
                # Don't fail the build on warnings, just report them
              
              else
                echo "✅ No Doxygen warnings found in $target_dir!"
              fi
            fi
          fi
        done
    
    - name: Prepare deployment files
      run: |
        cd doc
        echo "Preparing documentation for deployment..."
        
        # Create deployment directory
        mkdir -p ../deploy
        
        # Copy main documentation
        if [ -d "html" ]; then
          echo "Copying main documentation..."
          cp -r html ../deploy/
        else
          echo "Warning: Main html directory not found"
        fi
        
        # Copy target-specific documentation
        echo "Copying target-specific documentation..."
        for target_dir in */; do
          if [ -d "$target_dir/html" ] && [ "$target_dir" != "templates/" ]; then
            echo "Copying $target_dir documentation..."
            mkdir -p "../deploy/$target_dir"
            cp -r "$target_dir/html" "../deploy/$target_dir/"
          fi
        done
        
        # Filter out build artifacts and unnecessary files
        echo "Cleaning up deployment files..."
        cd ../deploy
        
        # Remove Doxygen build artifacts
        find . -name "*.md5" -delete 2>/dev/null || true
        find . -name "*.map" -delete 2>/dev/null || true
        find . -name "*.tmp" -delete 2>/dev/null || true
        find . -name "doxy.sourcelist" -delete 2>/dev/null || true
        find . -name "Doxyfile" -delete 2>/dev/null || true
        find . -name "DoxygenLayout_*.xml" -delete 2>/dev/null || true
        find . -name "doxygen_*.log" -delete 2>/dev/null || true
        find . -name "*.tag" -delete 2>/dev/null || true
        
        # Remove backup and temporary files
        find . -name "*~" -delete 2>/dev/null || true
        find . -name "*.bak" -delete 2>/dev/null || true
        find . -name ".DS_Store" -delete 2>/dev/null || true
        
        echo "Deployment preparation completed"
        
        # Show deployment statistics
        echo "Deployment statistics:"
        echo "  HTML files: $(find . -name "*.html" | wc -l)"
        echo "  CSS files:  $(find . -name "*.css" | wc -l)"
        echo "  JS files:   $(find . -name "*.js" | wc -l)"
        echo "  Image files: $(find . -name "*.png" -o -name "*.gif" -o -name "*.svg" -o -name "*.jpg" | wc -l)"
        echo "  Total size: $(du -sh . | cut -f1)"
   
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: libopencm3-documentation
        path: deploy/
        retention-days: 30
        compression-level: 6
    